name: Auto Update Ranking

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Executar Tracker
        env:
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
        run: |
          cd raid
          npm install axios
          node tracker_completo.js

      - name: Mover e Forçar Atualização
        run: |
          mkdir -p booyah-tracker/app
          cp raid/ranking.json booyah-tracker/app/ranking.json
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Limpa qualquer ficheiro que esteja a bloquear o processo
          git reset --hard HEAD
          
          # Traz as novidades do servidor e coloca as nossas mudanças no topo
          git pull origin main --rebase
          
          # Adiciona o novo ranking e envia
          git add booyah-tracker/app/ranking.json
          git commit -m "Auto-update: Ranking atualizado" || echo "Sem mudanças"
          git push origin main