- name: Instalar e Executar Tracker
        env:
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
        run: |
          cd raid
          npm install axios  # Só instalamos o axios, que é o que importa
          node tracker_completo.js