name: Auto Update Ranking

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dá permissão explícita para o robô escrever

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Baixa o histórico completo para evitar erros de sincronização

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar e Executar Tracker
        env:
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
        run: |
          cd raid
          npm install axios
          node tracker_completo.js

      - name: Mover ranking para a pasta do App
        run: |
          mkdir -p booyah-tracker/app
          cp raid/ranking.json booyah-tracker/app/ranking.json

      - name: Guardar alterações (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: Ranking atualizado via GitHub Actions"
          file_pattern: 'booyah-tracker/app/ranking.json'
          push_options: '--force' # Força o envio para resolver o erro [rejected]